### ISSUE TITLE
Sigar Fatal Error with Ryzen 5800x

### ISSUE THREAD

**Issue by fabio1999ita** [dyorgio/cpu-watcher#5]
i tried your app but i get error
[hs_err_pid6024.log](https://github.com/dyorgio/cpu-watcher/files/7352269/hs_err_pid6024.log)

**Comment by dyorgio** [comment]
Hello Fabio, thanks for hs_err file.
I have 2 suspicions: 

> C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe x86 loaded into memory

and

> Cygwin.

Could you try to use library outside Cygwin or adjusts PATH variable to don’t use/ref a x86 jvm?

**Comment by fabio1999ita** [comment]
i move default path to correct folder of java
![image](https://user-images.githubusercontent.com/27001568/137485513-58bea3e2-d77c-4146-8ebd-f51caf0be141.png)
but it didn't work
![image](https://user-images.githubusercontent.com/27001568/137486447-3ac7eaa1-ac4f-4d24-b38b-46a7228fbc3c.png)
also from intellij
![image](https://user-images.githubusercontent.com/27001568/137486546-8d03bead-c034-4049-b5b0-597cc5143af9.png)

**Comment by dyorgio** [comment]
Could you upload hs_err_pid1654.log? (Or the last hs_err generated file)

**Comment by fabio1999ita** [comment]
> Could you upload hs_err_pid1654.log? (Or the last hs_err generated file)

[hs_err_pid10356.log](https://github.com/dyorgio/cpu-watcher/files/7353431/hs_err_pid10356.log)
maybe problem can be `sigar`?

**Comment by dyorgio** [comment]
Yes sigar is an old lib, without maintence...
Try [this version](https://github.com/dyorgio/cpu-watcher/files/7354165/dyorgio.zip) without sigar dep.
You need to include this dep:
 ```
<dependency>
      <groupId>com.github.oshi</groupId>
      <artifactId>oshi-core-shaded</artifactId>
      <version>5.8.2</version>
  </dependency>
```

**Comment by fabio1999ita** [comment]
no way

![image](https://user-images.githubusercontent.com/27001568/137524893-cfe46567-a265-4e25-a840-66e4ac0ef957.png)


![image](https://user-images.githubusercontent.com/27001568/137524758-371351d9-d77f-4a94-bdd7-485f784bbdcb.png)

[hs_err_pid14984.log](https://github.com/dyorgio/cpu-watcher/files/7354828/hs_err_pid14984.log)

**Comment by dyorgio** [comment]
You are using maven dependency cpu-watcher:1.2.4...
Remove this dep from your project and paste source code of my last message ;).
https://github.com/dyorgio/cpu-watcher/files/7354165/dyorgio.zip

**Comment by fabio1999ita** [comment]
source added inside the project and now i get this error, i setted pid of CPUZ, i got a ryzen 5800x

![image](https://user-images.githubusercontent.com/27001568/137527852-4ba74944-43f2-40c4-9701-604f95f08bd4.png)


![image](https://user-images.githubusercontent.com/27001568/137527459-1973e9e5-38e5-4c11-97ac-f4bf71768e98.png)


`Exception in thread "CpuWatcher[PID:7960]" java.lang.StackOverflowError
        at java.io.InputStream.<init>(InputStream.java:45)
        at java.util.zip.ZipFile$ZipFileInputStream.<init>(ZipFile.java:711)
        at java.util.zip.ZipFile.getInputStream(ZipFile.java:375)
        at java.util.jar.JarFile.getInputStream(JarFile.java:448)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:1007)
        at sun.misc.Resource.cachedInputStream(Resource.java:77)
        at sun.misc.Resource.getByteBuffer(Resource.java:160)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at oshi.driver.windows.registry.ProcessPerformanceData.buildProcessMapFromRegistry(ProcessPerformanceData.java:69)
        at oshi.software.os.windows.WindowsOperatingSystem.queryProcessMapFromRegistry(WindowsOperatingSystem.java:340)
        at oshi.util.Memoizer$1.get(Memoizer.java:87)
        at oshi.software.os.windows.WindowsOperatingSystem.processMapToList(WindowsOperatingSystem.java:310)
        at oshi.software.os.windows.WindowsOperatingSystem.getProcess(WindowsOperatingSystem.java:304)
        at dyorgio.runtime.cpu.watcher.AbstractProcessWatcher.getCpuTimes(AbstractProcessWatcher.java:53)
        at dyorgio.runtime.cpu.watcher.CpuWatcher.run(CpuWatcher.java:109)`

**Comment by dyorgio** [comment]
Ow, sorry, this happens because I always put a lower stacksize value on my threads :).
Increase it on CpuWatcher class, line 50:
```java
super(group, null, "CpuWatcher[PID:" + pid + "]", 32l * 1024l);
```

Maybe to something like this:
```java
super(group, null, "CpuWatcher[PID:" + pid + "]", 10l * 32l * 1024l);
```

**Comment by fabio1999ita** [comment]
> ```java
> super(group, null, "CpuWatcher[PID:" + pid + "]", 10l * 32l * 1024l);
> ```

now program start but it doesn't limit the program

![image](https://user-images.githubusercontent.com/27001568/137530389-76b75739-4118-4384-aa23-beb6d41433b5.png)

Edit
i removed .join and now program start then finish, maybe it donesn't find the pid?

**Comment by dyorgio** [comment]
I only tested on my Mac :smile:.
Maybe cpu time is not ok on Windows.
Please, help me to test on Windows, include theses lines after cpuWatcher.start():
```java
while (true) {
    System.out.println("CPU: " + cpuWatcher.getCpuUsage());
    Thread.sleep(500);
}
```

Also, get sure that you are using correct PID.

**Comment by dyorgio** [comment]
Yes, without .join your java program exits, because CpuWatcher is a Daemon Thread.

**Comment by fabio1999ita** [comment]
![video](https://user-images.githubusercontent.com/27001568/137531574-9a5af69c-216d-42ae-90f0-1ec9c3865706.gif)

**Comment by dyorgio** [comment]
Could you wait more time? :smile:
Appears that it is working...

**Comment by fabio1999ita** [comment]
> Could you wait more time? 😄 Appears that it is working...

it's still running, and it's still working

**Comment by dyorgio** [comment]
So, fixed?

**Comment by fabio1999ita** [comment]
> So, fixed?

i wanna limit the cpu usage in that program, your loop just say me the cpu usage of the program but problem is that not limit usage of cpu

**Comment by dyorgio** [comment]
yes, it is working, this kind of program (benchmark) are supposed to use 100%, in your gif the max value is 80%.
Please, wait more time on test (30 seconds at last) and upload output.

**Comment by fabio1999ita** [comment]
if i wanna use like 50% of cpu in that program is correct this?

![image](https://user-images.githubusercontent.com/27001568/137532995-c10ed166-1afa-4739-b6ea-1d3c8de153b1.png)

**Comment by dyorgio** [comment]
Only if you want 50% of ALL CORES LOAD together.

**Comment by fabio1999ita** [comment]
after 1 min of stress test

![image](https://user-images.githubusercontent.com/27001568/137533427-0c4b4db0-a770-4568-9211-a5c9c2e20a7c.png)

**Comment by dyorgio** [comment]
I will download cpuz  and test it in a VM this weekend.
Could you repeat test using 3.5d as maximum percent? ( do not call setCpuLimit(null), it disables limiter)

**Comment by fabio1999ita** [comment]
> I will download cpuz and test it in a VM this weekend. Could you repeat test using 3.5d

what is 3.5d?

> ( do not call setCpuLimit(null), it disables limiter)

i just use the code in screen up

**Comment by dyorgio** [comment]
3.125d is equivalent a 50% of one core in your CPU:
100%/16 cores/2

**Comment by dyorgio** [comment]
Use it as limitUsage value

**Comment by fabio1999ita** [comment]
> 3.125d is equivalent a 50% of one core in your CPU: 100%/16 cores/2

but need float value, not double

**Comment by dyorgio** [comment]
ow! sorry again 😅 , use 3.125f so...

**Comment by fabio1999ita** [comment]
> 3.125f

ahhh ok, for this i tell you what is that xD

**Comment by fabio1999ita** [comment]
![image](https://user-images.githubusercontent.com/27001568/137539777-1d471275-7ee9-47d6-9062-4fa50a4f36c3.png)

**Comment by fabio1999ita** [comment]
but is normal that you program finish after i launch it if there aren't loop?
![image](https://user-images.githubusercontent.com/27001568/137539964-cce27cc4-79e6-4f85-be83-1c37b798a1ad.png)

**Comment by dyorgio** [comment]
First: you are not using it as a program, take a look on README, you are use it as a lib.

Yes, your program (Cpu) main method ends.
CpuWatcher is daemon by default ( it ends if no other thread (no daemon) is alive).
This is the behavior of Java Threads.
You have some options:
1) use .join()
2) use a loop (while (true) )
3) set cputWatcher as a normal Thread before .start(): cpuWatcher.setDaemon(false);

**Comment by fabio1999ita** [comment]
ah ok, i will wait news

**Comment by dyorgio** [comment]
But I'm curious now... did you try to use it as program?

java -jar cpu-watcher-1.2.4.jar 8685 3.125

Use release page artifact.

**Comment by fabio1999ita** [comment]
yes i had tried to launch it from batch file (the jar)

**Comment by dyorgio** [comment]
> ah ok, i will wait news

I got! On Windows 10 (not sure if old versions too) you needs admin provileges to SUSPEND/RESUME another process (owned or not by your user).

Again, you have some options:

1) Call it using a admin cmd.
2) Use my another lib: Run-As-Root.

**Comment by dyorgio** [comment]
Example using Run-As-Root: https://github.com/dyorgio/run-as-root

```java
public static void main(String[] args) throws Exception {
        RootExecutor executor = new RootExecutor();
        executor.run(() -> {
            CpuWatcher watcher = new CpuWatcher(8685, 3.125f);
            watcher.start();
            try {
                while (!Thread.currentThread().isInterrupted()) {
                    System.out.println(watcher.getCpuUsage());
                    Thread.sleep(1000);
                }
            } catch (InterruptedException ex) {
                Thread.currentThread().interrupt();
            }
        });
    }
```

**Comment by fabio1999ita** [comment]
it seems to work but can't keep the cpu stable, moreover it can be said that it doesn't work on processes that use few resources, like down of 5%

> Example using Run-As-Root: https://github.com/dyorgio/run-as-root
> 
> ```java
> public static void main(String[] args) throws Exception {
>         RootExecutor executor = new RootExecutor();
>         executor.run(() -> {
>             CpuWatcher watcher = new CpuWatcher(8685, 3.125f);
>             watcher.start();
>             try {
>                 while (!Thread.currentThread().isInterrupted()) {
>                     System.out.println(watcher.getCpuUsage());
>                     Thread.sleep(1000);
>                 }
>             } catch (InterruptedException ex) {
>                 Thread.currentThread().interrupt();
>             }
>         });
>     }
> ```

is normal that i can't see output after `executor.run(() -> {`?

**Comment by dyorgio** [comment]
Hello @fabio1999ita, try to use:

```java
cpuWatcher.setPriority(Thread.MAX_PRIORITY);
```

Before .start().

**Comment by dyorgio** [comment]
> is normal that i can't see output after executor.run(() -> {?

Yes, RootExecutor don't replicate out-process console output to host process.

**Comment by fabio1999ita** [comment]
> > is normal that i can't see output after executor.run(() -> {?
> 
> Yes, RootExecutor don't replicate out-process console output to host process.

so this code is useless
```java
try {
   while (!Thread.currentThread().isInterrupted()) {
      System.out.println(watcher.getCpuUsage());
      Thread.sleep(1000);
   }
} catch (InterruptedException ex) {
   Thread.currentThread().interrupt();
}
```

**Comment by fabio1999ita** [comment]
> Hello @fabio1999ita, try to use:
> 
> ```java
> cpuWatcher.setPriority(Thread.MAX_PRIORITY);
> ```
> 
> Before .start().

whit `15f` i get 50% of usage
![image](https://user-images.githubusercontent.com/27001568/137963604-d950f4be-52ce-43b8-b457-55ef278dee2d.png)

i used the Thread.MAX_PRIORITY

**Comment by fabio1999ita** [comment]
how can i limit a process that use only 6% of global cpu i tried also whit 0.05f but doesn't work

![image](https://user-images.githubusercontent.com/27001568/137964890-e87e1ca8-e9cf-4d41-a083-c3bbdc423882.png)

**Comment by dyorgio** [comment]
Hello @fabio1999ita, try out new version: 1.3.0, it is very more accurate in cpu limit feature.

To limit 6% of global cpu usage just pass `6.0f` as usageLimit arg.

Remember, this lib try at maximum to be accurate, but is always an approximation.

**Comment by fabio1999ita** [comment]
![image](https://user-images.githubusercontent.com/27001568/150652616-03a05fef-caa6-44f6-921a-28b1ea68e61c.png)

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference
	at dyorgio.runtime.out.process.OneRunOutProcess.call(OneRunOutProcess.java:277)
	at dyorgio.runtime.run.as.root.RootExecutor.execute(RootExecutor.java:148)
	at dyorgio.runtime.run.as.root.RootExecutor.run(RootExecutor.java:118)
	at cpu.main(cpu.java:7)
Caused by: java.lang.UnsatisfiedLinkError: Can't obtain class com.sun.jna.CallbackReference
	at com.sun.jna.Native.initIDs(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:248)
	at com.sun.jna.Structure.setAlignType(Structure.java:291)
	at com.sun.jna.Structure.<init>(Structure.java:208)
	at com.sun.jna.Structure.<init>(Structure.java:204)
	at com.sun.jna.Structure.<init>(Structure.java:191)
	at com.sun.jna.Structure.<init>(Structure.java:183)
	at com.sun.jna.platform.win32.WinNT$OSVERSIONINFOEX.<init>(WinNT.java:1980)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVersionOrGreater(VersionHelpers.java:59)
	at com.sun.jna.platform.win32.VersionHelpers.IsWindowsVistaOrGreater(VersionHelpers.java:127)
	at oshi.software.os.windows.WindowsOperatingSystem.<clinit>(WindowsOperatingSystem.java:109)
	at oshi.SystemInfo.createOperatingSystem(SystemInfo.java:104)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.SystemInfo.getOperatingSystem(SystemInfo.java:98)
	at dyorgio.runtime.cpu.watcher.CpuWatcher.<clinit>(CpuWatcher.java:33)
	at cpu.lambda$main$a06155df$1(cpu.java:8)
	at dyorgio.runtime.run.as.root.RootExecutor$RemoteCall.call(RootExecutor.java:172)
	at dyorgio.runtime.run.as.root.RootExecutor$RemoteCall.call(RootExecutor.java:155)
	at dyorgio.runtime.out.process.entrypoint.OneRunRemoteMain.main(OneRunRemoteMain.java:58)

Process finished with exit code 1
```

**Comment by dyorgio** [comment]
Broken release, try out 1.3.1.

**Comment by fabio1999ita** [comment]
> Broken release, try out 1.3.1.

this new version seems to work very well
could you make the breaks in the limited program shorter? and add search program by name as well as by pid?

**Comment by dyorgio** [comment]
> could you make the breaks in the limited program shorter? 

As I said, cpu-watcher try the best to be accurate, but is always an approximation... the breaks (sleeps) now are dynamic, and could be long if target process is a very expensive cpu one.
The idea is that in a long period of time, the median will be very near of target usage limit.
But you could try to play with sleeps direct on source :), take a look on line 160 (there is a max limit to sleep: 500ms, try to reduce it).

But I advise you: reduce sleep time on CpuWatcher thread cause more cpu consume of CpuWatcher lib.

> and add search program by name as well as by pid?

OSHI can do it for you, look this example:
```.java
int pid = new SystemInfo().getOperatingSystem().getProcesses(
    (OSProcess p) -> return p.getName().matches(".*MY QUERY.*")
, null, 1).get(0).getProcessID();
```

**Comment by fabio1999ita** [comment]
> OSHI can do it for you, look this example:

![image](https://user-images.githubusercontent.com/27001568/150682776-93c4a23f-b72e-4c05-ac37-c87af8ffd53f.png)

**Comment by dyorgio** [comment]
You probably is running on < java7, or using Kotlin instead...
You have 3 options to solve: use >= java8, use anonymous inner class or adjust code for Kotlin.

**Comment by fabio1999ita** [comment]
> You probably is running on < java7, or using Kotlin instead... You have 3 options to solve: use >= java8, use anonymous inner class or adjust code for Kotlin.

i'm not using kotlin (just maven) and i'm on java 8
![image](https://user-images.githubusercontent.com/27001568/150683872-a12b7cfd-20a6-466d-bde3-9d682c49e65e.png)

edit
oh problem was return, without it, it works

```java
int pid = new SystemInfo().getOperatingSystem().getProcesses(
    (OSProcess p) -> p.getName().matches(".*MY QUERY.*")
, null, 1).get(0).getProcessID();
```
add it in readme, that can be usefull

**Comment by dyorgio** [comment]
Oh, sorry, I see... just remove **return** keyword:

```java
int pid = new SystemInfo().getOperatingSystem().getProcesses(
    (OSProcess p) -> p.getName().matches(".*MY QUERY.*")
, null, 1).get(0).getProcessID();
```

@fabio1999ita I'm closing this issue, because now we are talking about doubts in Java Language and OSHI library... offtopic.

Please, if you have other problem with this lib, open another issue.
